### ISSUE TITLE
The SunRise returns a NULL.

### ISSUE THREAD

**Issue by Cliff2310** [shred/commons-suncalc#19]
Certain time return a NULL for times.getRise().

Here are the times I have found.  
All are the same location. 
 static double latitude  =   29.554532;  // geolocation 
 static double longitude =  -95.219382;  // Pearland, TX

The calling code is:
for( int i=1; i<range; i++){
		times = SunTimes.compute()
	            .on(time[i])       // set a date
	            .at(lat, lng)   // set a location
	            .execute();     // get the results
if( times.getRise() != null ) System.out.println(db._file_()+" <"+i+"> "+time[i]+" Rise "+times.getRise());		}

File1:
Input file is data and time from 1/1/19 to 12/31/19  every 15 min.
These are the values that returned a NULL. Range is the number of data points

(PowerDataAnalysis.java:542) < 375, Range 35044, last 135
(PowerDataAnalysis.java:522) <0> Tue Jan 01 00:00:00 CST 2019 /null
(PowerDataAnalysis.java:556) <17284> Sun Jun 30 01:00:00 CDT 2019 Rise null
(PowerDataAnalysis.java:556) <31971> Fri Nov 29 23:45:00 CST 2019 Rise null

File2:
This file is from 06/01/2018 00:15:00 to 12/31/2018 23:30:00

(PowerDataAnalysis.java:542) < 224, Range 20548, last 152
(PowerDataAnalysis.java:556) <2692> Fri Jun 29 01:00:00 CDT 2018 Rise null
(PowerDataAnalysis.java:556) <17475> Thu Nov 29 23:45:00 CST 2018 Rise null

As you can see the files are large. 
 All times are HH/00/00, HH/15/00, HH/30/00, or HH/45/00
******
**Work around**
IF NULL add 5 min. and re try.
temp.setTime(time[i].getTime() + TimeUnit.MINUTES.toMillis(5));
This removed all NULLs.
****
If you need anything else, please let me know.
Cliff

**Comment by shred** [comment]
Cliff, thank you reporting the issue!

I ran a test on your coordinates for the year 2019 with 15 minute intervals, and found these sunrises to be missing:

```
2019-07-13 06:30: null
2019-08-08 06:45: null
2019-09-04 07:00: null
2019-10-02 07:15: null
2019-10-26 07:30: null
2019-11-14 06:45: null
2019-12-03 07:00: null
2019-12-29 07:15: null
```

For example, on July 13th, the sun actually rises at almost exactly 06:30:00, which is also the start of the time range of the calculation.

Due to rounding errors, the sunrise is calculated slightly before that moment, say 06:29:59, while the next sunrise is computed for 06:30:01 the next day. It's the second half of the year, so the days are getting shorter and the sun is rising later each day, giving more than 24 hours between sunrises.

For this reason, there is no sunrise between July 13th 06:30 and July 14th 06:30. One sunrise is slightly before that window, the other slightly past that window.

I'm afraid you have just exceeded the precision limits of this library.

But on the other hand, as the sun is rising and setting only once a day, I see no good reason for computing the sunrise for every 15 minutes of the day, as you are getting (more or less) the same results all the time. You could always use midnight as the start:

```
times = SunTimes.compute()
    .on(time[i])
    .at(lat, lng)
    .midnight()      // <-- start at midnight of the day
    .execute();
```

There is not much else I can do, because the library is not intended to be that precise, so I am closing this bug.

**Comment by shred** [comment]
I forgot to mention: You can also use `.fullCycle()` and get the runrise of the next day instead of `null`:

```
times = SunTimes.compute()
    .on(time[i])
    .at(lat, lng)
    .fullCycle()
    .execute();
```

**Comment by Cliff2310** [comment]
The fullCucle() fixed my problems. Thanks for the quick response. I will withdraw (if possible) the issue report if you would like. 

I wanted to get the diurnal cycle to show along with the data.  The calling SunTimes at every point was just a first dive into the solar data. I was not sure how to present the data.  Now I only call SunTimes once a day.  I think what I really need is the sun angle.  
I would suggest you add  .midnight(), .fullCycle(), and any others to your SunCalc API or document them is some way. 

Thanks
Cliff

**Comment by shred** [comment]
If it's okay for you, I would like to keep this issue, so other people with a similar problem can search for it.

You are right, the `midnight()` and `fullCycle()` methods are very well hidden in the API documentation. Maybe I'll find some time this weekend, to add a chapter with some examples to the documentation.

**Comment by Cliff2310** [comment]
OK I'll leave it.  Some more documentation would be great! 
agin Thanks
Cliff

**Comment by shred** [comment]
I reviewed the documentation and added a lot of [examples](https://shredzone.org/maven/commons-suncalc/examples.html).
